### ISSUE TITLE
TypeError: Signature mismatch. Keys must be dtype <dtype: 'float32'>, got <dtype: 'string'>.

### ISSUE THREAD

**Issue by Haaarrrssshhh** [ElectroNath/-Training-an-Object-Detection-Model-with-TensorFlow-API-using-Google-COLAB#2]
got this while running the final train.py

**Comment by Haaarrrssshhh** [comment]
WARNING:tensorflow:
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

WARNING:tensorflow:From train.py:56: The name tf.logging.set_verbosity is deprecated. Please use tf.compat.v1.logging.set_verbosity instead.

WARNING:tensorflow:From train.py:56: The name tf.logging.INFO is deprecated. Please use tf.compat.v1.logging.INFO instead.

WARNING:tensorflow:From train.py:185: The name tf.app.run is deprecated. Please use tf.compat.v1.app.run instead.

WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/absl/app.py:250: main (from __main__) is deprecated and will be removed in a future version.
Instructions for updating:
Use object_detection/model_main.py.
W0430 10:46:36.150112 140421879846784 deprecation.py:323] From /usr/local/lib/python3.6/dist-packages/absl/app.py:250: main (from __main__) is deprecated and will be removed in a future version.
Instructions for updating:
Use object_detection/model_main.py.
WARNING:tensorflow:From train.py:91: The name tf.gfile.MakeDirs is deprecated. Please use tf.io.gfile.makedirs instead.

W0430 10:46:36.150411 140421879846784 module_wrapper.py:139] From train.py:91: The name tf.gfile.MakeDirs is deprecated. Please use tf.io.gfile.makedirs instead.

WARNING:tensorflow:From /content/gdrive/My Drive/Desktop/models/research/object_detection/utils/config_util.py:102: The name tf.gfile.GFile is deprecated. Please use tf.io.gfile.GFile instead.

W0430 10:46:36.151062 140421879846784 module_wrapper.py:139] From /content/gdrive/My Drive/Desktop/models/research/object_detection/utils/config_util.py:102: The name tf.gfile.GFile is deprecated. Please use tf.io.gfile.GFile instead.

WARNING:tensorflow:From train.py:96: The name tf.gfile.Copy is deprecated. Please use tf.io.gfile.copy instead.

W0430 10:46:36.157088 140421879846784 module_wrapper.py:139] From train.py:96: The name tf.gfile.Copy is deprecated. Please use tf.io.gfile.copy instead.

WARNING:tensorflow:From /content/gdrive/My Drive/Desktop/models/research/object_detection/legacy/trainer.py:267: create_global_step (from tensorflow.contrib.framework.python.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Please switch to tf.train.create_global_step
W0430 10:46:36.167924 140421879846784 deprecation.py:323] From /content/gdrive/My Drive/Desktop/models/research/object_detection/legacy/trainer.py:267: create_global_step (from tensorflow.contrib.framework.python.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Please switch to tf.train.create_global_step
WARNING:tensorflow:From /content/gdrive/My Drive/Desktop/models/research/object_detection/data_decoders/tf_example_decoder.py:182: The name tf.FixedLenFeature is deprecated. Please use tf.io.FixedLenFeature instead.

W0430 10:46:36.172853 140421879846784 module_wrapper.py:139] From /content/gdrive/My Drive/Desktop/models/research/object_detection/data_decoders/tf_example_decoder.py:182: The name tf.FixedLenFeature is deprecated. Please use tf.io.FixedLenFeature instead.

WARNING:tensorflow:From /content/gdrive/My Drive/Desktop/models/research/object_detection/data_decoders/tf_example_decoder.py:197: The name tf.VarLenFeature is deprecated. Please use tf.io.VarLenFeature instead.

W0430 10:46:36.173188 140421879846784 module_wrapper.py:139] From /content/gdrive/My Drive/Desktop/models/research/object_detection/data_decoders/tf_example_decoder.py:197: The name tf.VarLenFeature is deprecated. Please use tf.io.VarLenFeature instead.

WARNING:tensorflow:From /content/gdrive/My Drive/Desktop/models/research/object_detection/builders/dataset_builder.py:64: The name tf.gfile.Glob is deprecated. Please use tf.io.gfile.glob instead.

W0430 10:46:36.196138 140421879846784 module_wrapper.py:139] From /content/gdrive/My Drive/Desktop/models/research/object_detection/builders/dataset_builder.py:64: The name tf.gfile.Glob is deprecated. Please use tf.io.gfile.glob instead.

WARNING:tensorflow:From /content/gdrive/My Drive/Desktop/models/research/object_detection/builders/dataset_builder.py:71: The name tf.logging.warning is deprecated. Please use tf.compat.v1.logging.warning instead.

W0430 10:46:36.199252 140421879846784 module_wrapper.py:139] From /content/gdrive/My Drive/Desktop/models/research/object_detection/builders/dataset_builder.py:71: The name tf.logging.warning is deprecated. Please use tf.compat.v1.logging.warning instead.

WARNING:tensorflow:num_readers has been reduced to 1 to match input file shards.
W0430 10:46:36.199434 140421879846784 dataset_builder.py:72] num_readers has been reduced to 1 to match input file shards.
WARNING:tensorflow:From /content/gdrive/My Drive/Desktop/models/research/object_detection/builders/dataset_builder.py:86: parallel_interleave (from tensorflow.contrib.data.python.ops.interleave_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.data.experimental.parallel_interleave(...)`.
W0430 10:46:36.208488 140421879846784 deprecation.py:323] From /content/gdrive/My Drive/Desktop/models/research/object_detection/builders/dataset_builder.py:86: parallel_interleave (from tensorflow.contrib.data.python.ops.interleave_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.data.experimental.parallel_interleave(...)`.
WARNING:tensorflow:From /tensorflow-1.15.2/python3.6/tensorflow_core/contrib/data/python/ops/interleave_ops.py:77: parallel_interleave (from tensorflow.python.data.experimental.ops.interleave_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.data.Dataset.interleave(map_func, cycle_length, block_length, num_parallel_calls=tf.data.experimental.AUTOTUNE)` instead. If sloppy execution is desired, use `tf.data.Options.experimental_determinstic`.
W0430 10:46:36.208713 140421879846784 deprecation.py:323] From /tensorflow-1.15.2/python3.6/tensorflow_core/contrib/data/python/ops/interleave_ops.py:77: parallel_interleave (from tensorflow.python.data.experimental.ops.interleave_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.data.Dataset.interleave(map_func, cycle_length, block_length, num_parallel_calls=tf.data.experimental.AUTOTUNE)` instead. If sloppy execution is desired, use `tf.data.Options.experimental_determinstic`.
WARNING:tensorflow:From /content/gdrive/My Drive/Desktop/models/research/object_detection/builders/dataset_builder.py:155: DatasetV1.map_with_legacy_function (from tensorflow.python.data.ops.dataset_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.data.Dataset.map()
W0430 10:46:36.234148 140421879846784 deprecation.py:323] From /content/gdrive/My Drive/Desktop/models/research/object_detection/builders/dataset_builder.py:155: DatasetV1.map_with_legacy_function (from tensorflow.python.data.ops.dataset_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.data.Dataset.map()
WARNING:tensorflow:Entity <function build.<locals>.process_fn at 0x7fb61ef809d8> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: Bad argument number for Name: 3, expecting 4
W0430 10:46:36.261972 140421879846784 ag_logging.py:146] Entity <function build.<locals>.process_fn at 0x7fb61ef809d8> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: Bad argument number for Name: 3, expecting 4
Traceback (most recent call last):
  File "train.py", line 185, in <module>
    tf.app.run()
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "train.py", line 181, in main
    graph_hook_fn=graph_rewriter_fn)
  File "/content/gdrive/My Drive/Desktop/models/research/object_detection/legacy/trainer.py", line 281, in train
    train_config.prefetch_queue_capacity, data_augmentation_options)
  File "/content/gdrive/My Drive/Desktop/models/research/object_detection/legacy/trainer.py", line 60, in create_input_queue
    tensor_dict = create_tensor_dict_fn()
  File "train.py", line 122, in get_next
    dataset_builder.build(config)).get_next()
  File "/content/gdrive/My Drive/Desktop/models/research/object_detection/builders/dataset_builder.py", line 155, in build
    dataset = data_map_fn(process_fn, num_parallel_calls=num_parallel_calls)
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/data/ops/dataset_ops.py", line 1950, in map_with_legacy_function
    use_legacy_function=True))
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/data/ops/dataset_ops.py", line 3472, in __init__
    use_legacy_function=use_legacy_function)
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/data/ops/dataset_ops.py", line 2689, in __init__
    self._function.add_to_graph(ops.get_default_graph())
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/framework/function.py", line 545, in add_to_graph
    self._create_definition_if_needed()
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/framework/function.py", line 377, in _create_definition_if_needed
    self._create_definition_if_needed_impl()
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/framework/function.py", line 408, in _create_definition_if_needed_impl
    capture_resource_var_by_value=self._capture_resource_var_by_value)
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/framework/function.py", line 944, in func_graph_from_py_func
    outputs = func(*func_graph.inputs)
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/data/ops/dataset_ops.py", line 2681, in wrapper_fn
    ret = _wrapper_helper(*args)
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/data/ops/dataset_ops.py", line 2652, in _wrapper_helper
    ret = autograph.tf_convert(func, ag_ctx)(*nested_args)
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/autograph/impl/api.py", line 237, in wrapper
    raise e.ag_error_metadata.to_exception(e)
TypeError: in converted code:

    /content/gdrive/My Drive/Desktop/models/research/object_detection/builders/dataset_builder.py:134 process_fn
        processed_tensors = decoder.decode(value)
    /content/gdrive/My Drive/Desktop/models/research/object_detection/data_decoders/tf_example_decoder.py:388 decode
        tensors = decoder.decode(serialized_example, items=keys)
    /tensorflow-1.15.2/python3.6/tensorflow_core/contrib/slim/python/slim/data/tfexample_decoder.py:524 decode
        outputs.append(handler.tensors_to_item(keys_to_tensors))
    /content/gdrive/My Drive/Desktop/models/research/object_detection/data_decoders/tf_example_decoder.py:129 tensors_to_item
        item = self._handler.tensors_to_item(keys_to_tensors)
    /content/gdrive/My Drive/Desktop/models/research/object_detection/data_decoders/tf_example_decoder.py:98 tensors_to_item
        return tf.maximum(self._name_to_id_table.lookup(unmapped_tensor),
    /tensorflow-1.15.2/python3.6/tensorflow_core/python/ops/lookup_ops.py:223 lookup
        (self._key_dtype, keys.dtype))

    TypeError: Signature mismatch. Keys must be dtype <dtype: 'float32'>, got <dtype: 'string'>.

**Comment by ElectroNath** [comment]
Sorry for late reply chat me on WhatsApp +2348020891883
