### ISSUE TITLE
ModuleNotFoundError: No module named 'nets'

### ISSUE THREAD

**Issue by kajal-99** [ElectroNath/-Training-an-Object-Detection-Model-with-TensorFlow-API-using-Google-COLAB#3]
Traceback (most recent call last):
  File "model_builder_test.py", line 21, in <module>
    from object_detection.builders import model_builder
  File "/content/gdrive/My Drive/models/research/object_detection/builders/model_builder.py", line 59, in <module>
    from object_detection.models import faster_rcnn_inception_resnet_v2_feature_extractor as frcnn_inc_res
  File "/content/gdrive/My Drive/models/research/object_detection/models/faster_rcnn_inception_resnet_v2_feature_extractor.py", line 30, in <module>
    from nets import inception_resnet_v2
ModuleNotFoundError: No module named 'nets'

please help me to do this

**Comment by AdityaR-Bits** [comment]
nets will be located in your "slim" folder which is in the "research"  folder before "object_detection"

**Comment by ghost** [comment]
you need to export pythonpath. you can do this in colab with
```
import os
work_env_path = ':/content/gdrive/My Drive/models/:/content/gdrive/My Drive/models/research/:/content/gdrive/My Drive/models/research/slim'
os.environ['PYTHONPATH'] += work_env_path
```
